**Yours, Mine, and Ours: Do Divorce Laws Affect the Intertemporal Behavior
of Married Couples?**

*By Alessandra Voena*

Replicated by Saul Marenco

In [69]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
!pip install linearmodels
from linearmodels.panel import PanelOLS
from linearmodels.panel import RandomEffects
import econtools.metrics as mt


NLSW = pd.read_stata("/Users/saulmg/Downloads/116136-V1/replicate_empirics/NLSW_women.dta")
NLSW_c = pd.read_excel("/Users/saulmg/Downloads/116136-V1/replicate_empirics/NLSW_excel_cleaned.xlsx")

NLSW = NLSW.dropna()
NLSW

python(95550) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Requirement already satisfied: linearmodels in /opt/anaconda3/lib/python3.9/site-packages (5.1)
Requirement already satisfied: setuptools-scm[toml]<8.0.0,>=7.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from linearmodels) (7.1.0)
Requirement already satisfied: mypy-extensions>=0.4 in /opt/anaconda3/lib/python3.9/site-packages (from linearmodels) (0.4.3)
Requirement already satisfied: Cython>=0.29.34 in /opt/anaconda3/lib/python3.9/site-packages (from linearmodels) (0.29.35)
Requirement already satisfied: statsmodels>=0.12.0 in /opt/anaconda3/lib/python3.9/site-packages (from linearmodels) (0.13.2)
Requirement already satisfied: pandas>=1.1.0 in /opt/anaconda3/lib/python3.9/site-packages (from linearmodels) (1.4.4)
Requirement already satisfied: pyhdfe>=0.1 in /opt/anaconda3/lib/python3.9/site-packages (from linearmodels) (0.1.2)
Requirement already satisfied: numpy>=1.19.0 in /opt/anaconda3/lib/python3.9/site-packages (from linearmodels) (1.21.5)
Requirement already satisfied: scipy>=1.5.0 in /opt/anaconda3/lib/python3.9/site-packages (from linearmodels) (1.9.1)
Requirement already satisfied: formulaic>=0.6.1 in /opt/anaconda3/lib/python3.9/site-packages (from linearmodels) (0.6.3)
Requirement already satisfied: wrapt>=1.0 in /opt/anaconda3/lib/python3.9/site-packages (from formulaic>=0.6.1->linearmodels) (1.14.1)
Requirement already satisfied: interface-meta>=1.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from formulaic>=0.6.1->linearmodels) (1.3.0)
Requirement already satisfied: astor>=0.8 in /opt/anaconda3/lib/python3.9/site-packages (from formulaic>=0.6.1->linearmodels) (0.8.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from formulaic>=0.6.1->linearmodels) (4.3.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.1.0->linearmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.1.0->linearmodels) (2022.1)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.9/site-packages (from setuptools-scm[toml]<8.0.0,>=7.0.0->linearmodels) (21.3)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.9/site-packages (from setuptools-scm[toml]<8.0.0,>=7.0.0->linearmodels) (63.4.1)
Requirement already satisfied: tomli>=1.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from setuptools-scm[toml]<8.0.0,>=7.0.0->linearmodels) (2.0.1)
Requirement already satisfied: patsy>=0.5.2 in /opt/anaconda3/lib/python3.9/site-packages (from statsmodels>=0.12.0->linearmodels) (0.5.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/anaconda3/lib/python3.9/site-packages (from packaging>=20.0->setuptools-scm[toml]<8.0.0,>=7.0.0->linearmodels) (3.0.9)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.9/site-packages (from patsy>=0.5.2->statsmodels>=0.12.0->linearmodels) (1.16.0)

/opt/anaconda3/lib/python3.9/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Web Extension extension is not supported and will be removed
  for idx, row in parser.parse():

,year,assets,age,id,since1marr,std1,std2,std3,std4,std5,...,chd12,chd13,chd14,chd15,chd16,chd17,since1marr_2,since1marr_3,since1marr_4,since1marr_5
0,1967,1565.942505,33.0,352800000,15.0,0,1,0,0,0,...,0,0,0,0,0,0,225.0,3375.0,50625.0,759375.0
2,1967,20924.906250,37.0,308200000,22.0,0,1,0,0,0,...,0,0,0,0,0,0,484.0,10648.0,234256.0,5153632.0
3,1967,0.000000,39.0,347600000,17.0,0,1,0,0,0,...,0,0,0,0,0,0,289.0,4913.0,83521.0,1419857.0
6,1967,132228.187500,35.0,298900000,12.0,0,1,0,0,0,...,0,0,0,0,0,0,144.0,1728.0,20736.0,248832.0
7,1967,19770.023438,40.0,353100000,17.0,0,1,0,0,0,...,0,0,0,0,0,0,289.0,4913.0,83521.0,1419857.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45791,1993,30748.455078,49.0,2803,31.0,0,0,0,0,0,...,0,0,0,0,0,0,961.0,29791.0,923521.0,28629152.0
45792,1993,2803.535645,48.0,4689,29.0,0,0,0,0,0,...,0,0,0,0,0,0,841.0,24389.0,707281.0,20511148.0
45794,1995,13718.910156,50.0,4689,31.0,0,0,0,0,0,...,0,0,0,0,0,0,961.0,29791.0,923521.0,28629152.0
45797,1995,2572.295654,51.0,2803,33.0,0,0,0,0,0,...,0,0,0,0,0,0,1089.0,35937.0,1185921.0,39135392.0
45798,1997,27511.300781,53.0,2803,35.0,0,0,0,0,0,...,0,0,0,0,0,0,1225.0,42875.0,1500625.0,52521876.0

In [65]:
# Table 2 - Household Assets and Female Employment: Fixed Effects Regressions

### In the paper, this table estimates equation 4 using fixed-effect OLS regressions for different specification.
### Column 1 has the base, or control, specifications including age dummies for wife, year fixed-effects and individual
### effects. Column 2 also has controls for number of children in each household and column 3 adds state fixed effects.
### Column 4 uses a four degree polynomial in the years of marriage but many observations lack that data.
### There are 4 other columns that follow the same variables and fixed-effects, but columns 1 through 4 use the National
### Longitudinal Survey of Young and Mature Women (NLSW) data set, and columns 5 through 8 use the Panel Study of
### Income Dynamics data set (PSID).

### Results:
### We tried replicating this table in two different ways, both failing. The first method tried, was using "PanelOLS" from "linearmodels.panels",
### but the there was a clear mismatch between the number of dependent and independent variables, resulting in an error commented results). We
### tried cleaning the data both in python and manually in excel, and altering the code but the error persisted. We tried "PanelOLS()" because
### the author used "xtreg" in stata on their code, and "PanelOLS" was the closest translation in python, but it never worked. Later, we tried
### simple OLS regressiom with "statsmodels", which was able to run, but the results are extremely different. Again, we verified that
### the dataset had applicable observations but the results persisted. 
### 
### It is worth noting that on all 4 columns their correct dummy variables were selected, but in the table we can see that columns 2 through 4 have
### exactly the same results (We've checked that the variables are correct, too). Another interesting thing to note is that the four columns had
### the same number of observations, because our cleaned dataset has that many number of observations. Nonetheless, the dataset was thoroughly
### cleaned, resulting in those 12,022 observations. I assume that not by coincidence this is the number of observations column 4 should have.

##################################################################################################################################################################
## First Column

y1 = ["assets"]
x1 = ["uni_comprop","uni_title", "uni_eqdistr", "comprop", "eqdistr", "d_age1", "d_age2", "d_age3", "d_age4", "d_age5", "d_age6", "d_age7", "d_age8", "d_age9", \
     "d_age10", "d_age11", "d_age12", "d_age13", "d_age14", "d_age15", "d_age16", "d_age17", "d_age18", "d_age19", "d_age20", "d_age21", "d_age22", "d_age23", \
     "d_age24", "d_age25", "d_age26", "d_age27", "d_age28", "d_age29", "d_age30", "d_age31", "d_age32", "d_age33", "d_age34", "d_age35", "d_age36", "d_age37", \
     "d_age38", "d_age39", "d_age40", "d_age41", "d_age42", "d_age43", "d_age44", "d_age45", "d_age46", "d_age47", "d_age48", "d_age49", "d_age50", "d_age51", \
     "d_age52", "d_age53", "d_age54", "d_age55", "d_age56", "d_age57", "d_age58", "d_age59", "d_age60", "d_age61", "d_age62", "d_age63", "d_age64", "d_age65", \
     "d_age66", "d_age67", "yrd1", "yrd2", "yrd3", "yrd4", "yrd5", "yrd6", "yrd7", "yrd8", "yrd9", "yrd10", "yrd11", "yrd12", "yrd13", "yrd14", "yrd15", "yrd16", \
     "yrd17", "yrd18", "yrd19", "yrd20", "yrd21", "yrd22", "yrd23", "yrd24", "yrd25", "yrd26", "yrd27", "yrd28", "yrd29", "yrd30", "yrd31"] 


X1 = NLSW_c[x1]
Y1 = NLSW_c[y1]

model1= sm.OLS(Y1,X1)

results1= model1.fit()

uni_c1 = np.round(results1.params["uni_comprop"]).astype(int)
uni_c1std = np.round(results1.bse["uni_comprop"]).astype(int)

uni_t1 = np.round(results1.params["uni_title"]).astype(int)
uni_t1std = np.round(results1.bse["uni_title"]).astype(int)

uni_e1 = np.round(results1.params["uni_eqdistr"]).astype(int)
uni_e1std = np.round(results1.bse["uni_eqdistr"]).astype(int)

c1 = np.round(results1.params["comprop"]).astype(int)
c1std = np.round(results1.bse["comprop"]).astype(int)

eq1 = np.round(results1.params["eqdistr"]).astype(int)
eq1std = np.round(results1.bse["eqdistr"]).astype(int)


##################################################################################################################################################################

## Column 2

y1 = ["assets"]
x1 = ["uni_comprop","uni_title", "uni_eqdistr", "comprop", "eqdistr", "d_age1", "d_age2", "d_age3", "d_age4", "d_age5", "d_age6", "d_age7", "d_age8", "d_age9", \
     "d_age10", "d_age11", "d_age12", "d_age13", "d_age14", "d_age15", "d_age16", "d_age17", "d_age18", "d_age19", "d_age20", "d_age21", "d_age22", "d_age23", \
     "d_age24", "d_age25", "d_age26", "d_age27", "d_age28", "d_age29", "d_age30", "d_age31", "d_age32", "d_age33", "d_age34", "d_age35", "d_age36", "d_age37", \
     "d_age38", "d_age39", "d_age40", "d_age41", "d_age42", "d_age43", "d_age44", "d_age45", "d_age46", "d_age47", "d_age48", "d_age49", "d_age50", "d_age51", \
     "d_age52", "d_age53", "d_age54", "d_age55", "d_age56", "d_age57", "d_age58", "d_age59", "d_age60", "d_age61", "d_age62", "d_age63", "d_age64", "d_age65", \
     "d_age66", "d_age67", "yrd1", "yrd2", "yrd3", "yrd4", "yrd5", "yrd6", "yrd7", "yrd8", "yrd9", "yrd10", "yrd11", "yrd12", "yrd13", "yrd14", "yrd15", "yrd16", \
     "yrd17", "yrd18", "yrd19", "yrd20", "yrd21", "yrd22", "yrd23", "yrd24", "yrd25", "yrd26", "yrd27", "yrd28", "yrd29", "yrd30", "yrd31", "chd1", "chd2", "chd3", \
     "chd4", "chd5", "chd6", "chd7", "chd8", "chd9", "chd10", "chd11", "chd12", "chd13", "chd14", "chd15", "chd16", "chd17"] 


X1 = NLSW_c[x1]
Y1 = NLSW_c[y1]

model2= sm.OLS(Y,X)

results2= model2.fit()

uni_c2 = np.round(results2.params["uni_comprop"]).astype(int)
uni_c2std = np.round(results2.bse["uni_comprop"]).astype(int)

uni_t2 = np.round(results2.params["uni_title"]).astype(int)
uni_t2std = np.round(results2.bse["uni_title"]).astype(int)

uni_e2 = np.round(results2.params["uni_eqdistr"]).astype(int)
uni_e2std = np.round(results2.bse["uni_eqdistr"]).astype(int)

c2 = np.round(results2.params["comprop"]).astype(int)
c2std = np.round(results2.bse["comprop"]).astype(int)

eq2 = np.round(results2.params["eqdistr"]).astype(int)
eq2std = np.round(results2.bse["eqdistr"]).astype(int)


##################################################################################################################################################################

## Column 3

y1 = ["assets"]
x1 = ["uni_comprop","uni_title", "uni_eqdistr", "comprop", "eqdistr", "d_age1", "d_age2", "d_age3", "d_age4", "d_age5", "d_age6", "d_age7", "d_age8", "d_age9", \
     "d_age10", "d_age11", "d_age12", "d_age13", "d_age14", "d_age15", "d_age16", "d_age17", "d_age18", "d_age19", "d_age20", "d_age21", "d_age22", "d_age23", \
     "d_age24", "d_age25", "d_age26", "d_age27", "d_age28", "d_age29", "d_age30", "d_age31", "d_age32", "d_age33", "d_age34", "d_age35", "d_age36", "d_age37", \
     "d_age38", "d_age39", "d_age40", "d_age41", "d_age42", "d_age43", "d_age44", "d_age45", "d_age46", "d_age47", "d_age48", "d_age49", "d_age50", "d_age51", \
     "d_age52", "d_age53", "d_age54", "d_age55", "d_age56", "d_age57", "d_age58", "d_age59", "d_age60", "d_age61", "d_age62", "d_age63", "d_age64", "d_age65", \
     "d_age66", "d_age67", "yrd1", "yrd2", "yrd3", "yrd4", "yrd5", "yrd6", "yrd7", "yrd8", "yrd9", "yrd10", "yrd11", "yrd12", "yrd13", "yrd14", "yrd15", "yrd16", \
     "yrd17", "yrd18", "yrd19", "yrd20", "yrd21", "yrd22", "yrd23", "yrd24", "yrd25", "yrd26", "yrd27", "yrd28", "yrd29", "yrd30", "yrd31", "chd1", "chd2", "chd3", \
     "chd4", "chd5", "chd6", "chd7", "chd8", "chd9", "chd10", "chd11", "chd12", "chd13", "chd14", "chd15", "chd16", "chd17", "std1", "std2", "std3", "std4", "std5", \
     "std6", "std7", "std8", "std9", "std10", "std11", "std12", "std13", "std14", "std15", "std16", "std17", "std18", "std19", "std20", "std21", "std22", "std23", \
     "std24", "std25", "std26", "std27", "std28", "std29", "std30", "std31", "std32", "std33", "std34", "std35", "std36", "std37", "std38", "std39", "std40", "std41", \
     "std42", "std43", "std44", "std45", "std46", "std47", "std48", "std49", "std50"] 


X1 = NLSW_c[x1]
Y1 = NLSW_c[y1]

model3= sm.OLS(Y,X)

results3= model3.fit()

uni_c3 = np.round(results3.params["uni_comprop"]).astype(int)
uni_c3std = np.round(results3.bse["uni_comprop"]).astype(int)

uni_t3 = np.round(results3.params["uni_title"]).astype(int)
uni_t3std = np.round(results3.bse["uni_title"]).astype(int)

uni_e3 = np.round(results3.params["uni_eqdistr"]).astype(int)
uni_e3std = np.round(results3.bse["uni_eqdistr"]).astype(int)

c3 = np.round(results3.params["comprop"]).astype(int)
c3std = np.round(results3.bse["comprop"]).astype(int)

eq3 = np.round(results2.params["eqdistr"]).astype(int)
eq3std = np.round(results3.bse["eqdistr"]).astype(int)


##################################################################################################################################################################

## Column 4

y1 = ["assets"]
x1 = ["uni_comprop","uni_title", "uni_eqdistr", "comprop", "eqdistr", "d_age1", "d_age2", "d_age3", "d_age4", "d_age5", "d_age6", "d_age7", "d_age8", "d_age9", \
     "d_age10", "d_age11", "d_age12", "d_age13", "d_age14", "d_age15", "d_age16", "d_age17", "d_age18", "d_age19", "d_age20", "d_age21", "d_age22", "d_age23", \
     "d_age24", "d_age25", "d_age26", "d_age27", "d_age28", "d_age29", "d_age30", "d_age31", "d_age32", "d_age33", "d_age34", "d_age35", "d_age36", "d_age37", \
     "d_age38", "d_age39", "d_age40", "d_age41", "d_age42", "d_age43", "d_age44", "d_age45", "d_age46", "d_age47", "d_age48", "d_age49", "d_age50", "d_age51", \
     "d_age52", "d_age53", "d_age54", "d_age55", "d_age56", "d_age57", "d_age58", "d_age59", "d_age60", "d_age61", "d_age62", "d_age63", "d_age64", "d_age65", \
     "d_age66", "d_age67", "yrd1", "yrd2", "yrd3", "yrd4", "yrd5", "yrd6", "yrd7", "yrd8", "yrd9", "yrd10", "yrd11", "yrd12", "yrd13", "yrd14", "yrd15", "yrd16", \
     "yrd17", "yrd18", "yrd19", "yrd20", "yrd21", "yrd22", "yrd23", "yrd24", "yrd25", "yrd26", "yrd27", "yrd28", "yrd29", "yrd30", "yrd31", "chd1", "chd2", "chd3", \
     "chd4", "chd5", "chd6", "chd7", "chd8", "chd9", "chd10", "chd11", "chd12", "chd13", "chd14", "chd15", "chd16", "chd17", "std1", "std2", "std3", "std4", "std5", \
     "std6", "std7", "std8", "std9", "std10", "std11", "std12", "std13", "std14", "std15", "std16", "std17", "std18", "std19", "std20", "std21", "std22", "std23", \
     "std24", "std25", "std26", "std27", "std28", "std29", "std30", "std31", "std32", "std33", "std34", "std35", "std36", "std37", "std38", "std39", "std40", "std41", \
     "std42", "std43", "std44", "std45", "std46", "std47", "std48", "std49", "std50"] 


X1 = NLSW_c[x1]
Y1 = NLSW_c[y1]

model4= sm.OLS(Y,X)

results4= model4.fit()

uni_c4 = np.round(results4.params["uni_comprop"]).astype(int)
uni_c4std = np.round(results4.bse["uni_comprop"]).astype(int)

uni_t4 = np.round(results4.params["uni_title"]).astype(int)
uni_t4std = np.round(results4.bse["uni_title"]).astype(int)

uni_e4 = np.round(results4.params["uni_eqdistr"]).astype(int)
uni_e4std = np.round(results4.bse["uni_eqdistr"]).astype(int)

c4 = np.round(results4.params["comprop"]).astype(int)
c4std = np.round(results4.bse["comprop"]).astype(int)

eq4 = np.round(results4.params["eqdistr"]).astype(int)
eq4std = np.round(results4.bse["eqdistr"]).astype(int)


##################################################################################################################################################################
##################################################################################################################################################################

print("""Table 2-HOUSEHOLDS AND FEMALE EMPLOYMENT: FIXED EFFECTS REGRESSIONS
---------------------------------------------------------------------
                Assets         Assets         Assets         Assets
                NLSW           NLSW           NLSW           NLSW
Variables       (1)            (2)            (3)            (4)
---------------------------------------------------------------------
uni_comprop     {}          {}          {}          {}          
                ({})         ({})         ({})         ({})
uni_title       {}          {}          {}          {}
                ({})         ({})         ({})         ({})
uni_eqdistr     {}          {}          {}          {}
                ({})         ({})         ({})         ({})
comprop         {}           {}           {}           {}
                ({})         ({})         ({})         ({})
eqdistr         {}           {}           {}           {}
                ({})         ({})         ({})         ({})

Fxd Efcs
Year            Yes            Yes            Yes            Yes
Age             Yes            Yes            Yes            Yes
Children        No             Yes            Yes            Yes
State           No             No             Yes            Yes
Polyn yrs.      No             No             No             Yes
married

Observations    {}          {}          {}          {}
""".format(uni_c1, uni_c2, uni_c3, uni_c4,
           uni_c1std, uni_c2std, uni_c3std, uni_c4std,
           uni_t1, uni_t2, uni_t4, uni_t4,
           uni_t1std, uni_t2std, uni_t3std, uni_t4std,
           uni_e1, uni_e2, uni_e3, uni_e4,
           uni_e1std, uni_e2std, uni_e3std, uni_e4std,
           c1, c2, c3, c4,
           c1std, c2std, c3std, c4std,
           eq1, eq2, eq3, eq4,
           eq1std, eq2std, eq3std, eq4std,
           int(results1.nobs), int(results2.nobs), int(results3.nobs), int(results4.nobs)))

Table 2-HOUSEHOLDS AND FEMALE EMPLOYMENT: FIXED EFFECTS REGRESSIONS
---------------------------------------------------------------------
                Assets         Assets         Assets         Assets
                NLSW           NLSW           NLSW           NLSW
Variables       (1)            (2)            (3)            (4)
---------------------------------------------------------------------
uni_comprop     21392          20248          20248          20248
                (5278)         (5275)         (5275)         (5275)
uni_title       -8976          -9471          -9471          -9471
                (5435)         (5431)         (5431)         (5431)
uni_eqdistr     14147          13483          13483          13483
                (5220)         (5217)         (5217)         (5217)
comprop         6553           6793           6793           6793
                (4304)         (4295)         (4295)         (4295)
eqdistr         9930           9314           9314           9314
                (4786)         (4754)         (4754)         (4754)

Fxd Efcs
Year            Yes            Yes            Yes            Yes
Age             Yes            Yes            Yes            Yes
Children        No             Yes            Yes            Yes
State           No             No             Yes            Yes
Polyn yrs.      No             No             No             Yes
married

Observations    12022          12022          12022          12022