In [10]:
import pandas as pd
import numpy as np

In [11]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [46]:
data = pd.read_stata("/Users/adishsundar/Desktop/Salem Center Research/WWOH Saudi/replication_package/data/clean_data/01_main_exp_clean.dta")
df = data
data.head()

,age,education,employed_now,employed_wife,children,haafez_self,vjobs_self,mwage_self,mwage_others,mwage_confidence,outside_self,outside_others,outside_confidence,semiseg_self,semiseg_others,semiseg_confidence,labor_demand_guess,session,signed_up_number,condition2,college_deg,married,num_know_per,num_mfs_per,stag,outside_guess,outside_objective,outside_wedge,semiseg_guess,semiseg_objective,semiseg_wedge,mwage_guess,mwage_objective,mwage_wedge,outside_wedge_pos,interaction
0,24.0,diploma,1,1,2,1,1,1,3,4,1,29,5,1,27,4,92.0,1,1.0,0.0,0.0,1.0,0.966667,0.500000,1,30.0,27.0,3.0,28.0,23.0,5.0,4.0,18.0,-14.0,1.0,0.0
1,20.0,secondary,1,1,2,1,1,0,12,3,1,22,3,1,14,2,27.0,1,0.0,1.0,0.0,1.0,0.966667,0.333333,0,23.0,27.0,-4.0,15.0,23.0,-8.0,12.0,18.0,-6.0,0.0,0.0
2,28.0,secondary,0,0,0,1,1,0,20,3,1,25,3,1,24,3,50.0,1,0.0,0.0,0.0,1.0,0.000000,0.000000,0,26.0,27.0,-1.0,25.0,23.0,2.0,20.0,18.0,2.0,0.0,0.0
3,18.0,secondary,1,0,1,1,1,1,15,4,1,19,5,1,26,4,20.0,1,0.0,0.0,0.0,1.0,0.966667,0.966667,0,20.0,27.0,-7.0,27.0,23.0,4.0,16.0,18.0,-2.0,0.0,0.0
4,29.0,bachelor,1,1,2,0,1,1,16,4,1,28,5,1,24,5,75.0,1,0.0,0.0,1.0,1.0,0.966667,0.333333,0,29.0,27.0,2.0,25.0,23.0,2.0,17.0,18.0,-1.0,1.0,0.0

In [ ]:
# Main Experiment Summary Statistics

# These are the same as the researcher's result

In [29]:
import pandas as pd
import numpy as np

# List of variables to summarize
sum_vars = ["age", "college_deg", "children", "employed_now", "employed_wife", 
            "num_know_per", "num_mfs_per"]

# Labels for variables
var_labels = {
    "age": "Age",
    "college_deg": "College Degree (%)",
    "children": "Number of Children",
    "employed_now": "Employed (%)",
    "employed_wife": "Wife Employed (%)",
    "num_know_per": "Other Participants Known (%)",
    "num_mfs_per": "Other Participants with Mutual Friends (%)",
}

# Initialize dictionaries to store summary statistics
summary_stats = {}
for var in sum_vars:
    summary_stats[var] = {"all": {}, "0": {}, "1": {}}

# Loop through variables
for var in sum_vars:
    for i in [0, 1]:
        # Calculate mean and standard deviation for treatment and control
        summary_stats[var][str(i)]["mean"] = data.loc[data["condition2"] == i, var].mean()
        summary_stats[var][str(i)]["sd"] = data.loc[data["condition2"] == i, var].std()

    # Calculate mean and standard deviation for the full sample
    summary_stats[var]["all"]["mean"] = data[var].mean()
    summary_stats[var]["all"]["sd"] = data[var].std()

# Print summary statistics
for var in sum_vars:
    print(f"{var_labels[var]} & {summary_stats[var]['all']['mean']:.2f} & {summary_stats[var]['0']['mean']:.2f} & {summary_stats[var]['1']['mean']:.2f} \\\\")
    print(f" & ({summary_stats[var]['all']['sd']:.2f}) & ({summary_stats[var]['0']['sd']:.2f}) & ({summary_stats[var]['1']['sd']:.2f}) \\\\")

# Number of observations
count_all = len(data)
count_0 = data[data["condition2"] == 0].shape[0]
count_1 = data[data["condition2"] == 1].shape[0]

print(f"\nN & {count_all} & {count_0} & {count_1} \\\\")

Age & 24.78 & 24.64 & 24.91 \\
 & (4.21) & (3.99) & (4.41) \\
College Degree (%) & 0.56 & 0.55 & 0.57 \\
 & (0.50) & (0.50) & (0.50) \\
Number of Children & 1.71 & 1.64 & 1.77 \\
 & (1.72) & (1.70) & (1.74) \\
Employed (%) & 0.87 & 0.87 & 0.86 \\
 & (0.34) & (0.33) & (0.35) \\
Wife Employed (%) & 0.65 & 0.66 & 0.65 \\
 & (0.48) & (0.48) & (0.48) \\
Other Participants Known (%) & 0.51 & 0.50 & 0.53 \\
 & (0.38) & (0.39) & (0.38) \\
Other Participants with Mutual Friends (%) & 0.39 & 0.38 & 0.40 \\
 & (0.35) & (0.35) & (0.35) \\

N & 500 & 247 & 253 \\

In [ ]:
# Main Experiment - Table 5: Effect of Belief Update on Job-Matching Service Sign-Up

# For this code output, the results were the same except for p-values.
# As can be seen below, the R-squared values are mostly identical to the researcher's output.
# The robust p-values are relatively similar, however the wild boostrap and permutation test p-values are 
# very different, but this is most likely a difference in the way these values were calcualted (such as differences
# in boostrapping, etc.)

# I tried a lot of different variations to get p-value results, but this was generally the repeated outcome.

In [53]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.iolib.summary2 import summary_col

# Create the 'update' variable
data['update'] = data['outside_wedge'] * (data['condition2'] == 1)

# Replace 'update' values for condition2 == 0
data.loc[data['condition2'] == 0, 'update'] = 0

# Model specifications
specs = [
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence',
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence + C(session)',
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence + C(session) + employed_wife + employed_now + education + children + num_know_per + num_mfs_per + age'
]

# Create a list to store regression results
results = []

# Loop through the specifications
for i, spec in enumerate(specs, start=1):
    # Fit the regression model
    model = sm.OLS.from_formula(spec, data=data)
    result = model.fit()

    # Append results to the list
    results.append(result)

# Combine results into a summary table
table = summary_col(results, stars=True, model_names=['Model 1', 'Model 2', 'Model 3'], info_dict={'R-squared': lambda x: f"{x.rsquared:.4f}"} )

# Display the table
print(table)

=======================================================
                             Model 1  Model 2  Model 3
-------------------------------------------------------
C(session)[T.10]                      0.0435   0.0618
                                      (0.1153) (0.1206)
C(session)[T.11]                      0.0415   0.0247
                                      (0.1119) (0.1199)
C(session)[T.12]                      0.0665   0.0509
                                      (0.1148) (0.1256)
C(session)[T.13]                      0.2059*  0.1796
                                      (0.1160) (0.1258)
C(session)[T.14]                      0.2837** 0.2796**
                                      (0.1142) (0.1238)
C(session)[T.15]                      0.2630** 0.2520**
                                      (0.1156) (0.1214)
C(session)[T.16]                      -0.0395  -0.0678
                                      (0.1180) (0.1259)
C(session)[T.17]                      0.0073   0.0044
                                      (0.1159) (0.1266)
C(session)[T.2]                       0.0534   0.0904
                                      (0.1102) (0.1135)
C(session)[T.3]                       0.1302   0.1475
                                      (0.1146) (0.1174)
C(session)[T.4]                       0.1309   0.1228
                                      (0.1143) (0.1181)
C(session)[T.5]                       0.2775** 0.2692**
                                      (0.1149) (0.1243)
C(session)[T.6]                       0.1466   0.1468
                                      (0.1138) (0.1221)
C(session)[T.7]                       0.0680   0.0913
                                      (0.1147) (0.1208)
C(session)[T.8]                       0.2492** 0.2558**
                                      (0.1136) (0.1212)
C(session)[T.9]                       0.2496** 0.2601**
                                      (0.1178) (0.1222)
Intercept                   -0.0255   -0.1158  -0.1271
                            (0.0857)  (0.1215) (0.1891)
R-squared                   0.0270    0.0798   0.0926
R-squared Adj.              0.0192    0.0414   0.0292
age                                            0.0002
                                               (0.0064)
children                                       0.0096
                                               (0.0147)
education[T.bachelor]                          0.0487
                                               (0.0651)
education[T.diploma]                           0.0221
                                               (0.0644)
education[T.masters]                           0.0308
                                               (0.0908)
education[T.middle]                            0.0523
                                               (0.1839)
education[T.other_postgrad]                    -0.2995
                                               (0.2036)
education[T.phd]                               0.0019
                                               (0.1587)
education[T.primary]                           -0.0000
                                               (0.0000)
education[T.secondary]                         0.0166
                                               (0.0635)
employed_now                                   -0.0519
                                               (0.0662)
employed_wife                                  0.0547
                                               (0.0487)
num_know_per                                   -0.0757
                                               (0.0629)
num_mfs_per                                    0.1252*
                                               (0.0656)
outside_confidence          0.0264    0.0227   0.0237
                            (0.0212)  (0.0211) (0.0220)
outside_others              0.0049    0.0057   0.0053
                            (0.0035)  (0.0036) (0.0037)
outside_self                0.1095*   0.0696   0.0320
                            (0.0604)  (0.0616) (0.0688)
update                      -0.0076** -0.0065* -0.0068*
                            (0.0034)  (0.0035) (0.0036)
R-squared                   0.0270    0.0798   0.0926
=======================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

In [ ]:
# p-value results

In [55]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.iolib.summary2 import summary_col

# Assuming 'data' is your DataFrame
# Replace 'data' with the actual variable name you have in Python

# Create the 'update' variable
data['update'] = data['outside_wedge'] * (data['condition2'] == 1)

# Replace 'update' values for condition2 == 0
data.loc[data['condition2'] == 0, 'update'] = 0

# Model specifications
specs = [
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence',
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence + C(session)',
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence + C(session) + employed_wife + employed_now + education + children + num_know_per + num_mfs_per + age'
]

# Create a list to store p-values
p_values = []

# Loop through the specifications
for i, spec in enumerate(specs, start=1):
    # Fit the regression model
    model = sm.OLS.from_formula(spec, data=data)
    result = model.fit()

    # Get the p-value for the 'update' variable
    p_value = result.pvalues['update']

    # Append p-value to the list
    p_values.append(p_value)

# Display the p-values
for i, p_value in enumerate(p_values, start=1):
    print(f"Model {i} Robust SE p-value for 'update': {p_value:.4f}")

Model 1 Robust SE p-value for 'update': 0.0267
Model 2 Robust SE p-value for 'update': 0.0638
Model 3 Robust SE p-value for 'update': 0.0580

In [61]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
import bootstrapped.bootstrap as bs
import bootstrapped.stats_functions as bs_stats

# Assuming 'data' is your DataFrame
# Replace 'data' with the actual variable name you have in Python

# Create the 'update' variable
data['update'] = data['outside_wedge'] * (data['condition2'] == 1)

# Replace 'update' values for condition2 == 0
data.loc[data['condition2'] == 0, 'update'] = 0

# Model specifications
specs = [
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence',
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence + C(session)',
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence + C(session) + employed_wife + employed_now + education + children + num_know_per + num_mfs_per + age'
]

# Create a list to store p-values
p_values = []

# Set the number of bootstrap samples
num_bootstrap_samples = 1000

# Loop through the specifications
for i, spec in enumerate(specs, start=1):
    # Fit the regression model
    model = sm.OLS.from_formula(spec, data=data)
    result = model.fit()

    # Get the bootstrap p-value for the 'update' variable
    values = np.array(result.resid)
    bootstrap_result = bs.bootstrap(values, stat_func=bs_stats.mean, num_iterations=num_bootstrap_samples)
    p_value = bootstrap_result.lower_bound + (1 - bootstrap_result.upper_bound)

    # Append p-value to the list
    p_values.append(p_value)

# Display the bootstrap p-values
for i, p_value in enumerate(p_values, start=1):
    print(f"Model {i} Wild Bootstrap p-value for 'update': {p_value:.4f}")

Model 1 Wild Bootstrap p-value for 'update': 0.9214
Model 2 Wild Bootstrap p-value for 'update': 0.9201
Model 3 Wild Bootstrap p-value for 'update': 0.9218

In [64]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
from permute.core import one_sample

# Assuming 'data' is your DataFrame
# Replace 'data' with the actual variable name you have in Python

# Create the 'update' variable
data['update'] = data['outside_wedge'] * (data['condition2'] == 1)

# Replace 'update' values for condition2 == 0
data.loc[data['condition2'] == 0, 'update'] = 0

# Model specifications
specs = [
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence',
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence + C(session)',
    'signed_up_number ~ update + outside_self + outside_others + outside_confidence + C(session) + employed_wife + employed_now + education + children + num_know_per + num_mfs_per + age'
]

# Create a list to store p-values
p_values = []

# Set the number of permutations
num_permutations = 1000

# Loop through the specifications
for i, spec in enumerate(specs, start=1):
    # Fit the regression model
    model = sm.OLS.from_formula(spec, data=data)
    result = model.fit()

    # Permutation test
    permuted_stats = one_sample(data['signed_up_number'], np.random.permutation(data['update']), reps=num_permutations)

    # Calculate the p-value
    obs_statistic = result.params['update'] / result.bse['update']
    p_value = np.sum(np.abs(permuted_stats) >= np.abs(obs_statistic)) / num_permutations

    # Append p-value to the list
    p_values.append(p_value)

# Display the permutation test p-values
for i, p_value in enumerate(p_values, start=1):
    print(f"Model {i} Permutation Test p-value for 'update': {p_value:.4f}")

Model 1 Permutation Test p-value for 'update': 0.0010
Model 2 Permutation Test p-value for 'update': 0.0010
Model 3 Permutation Test p-value for 'update': 0.0010

In [238]:
# Main Experiment - Table 2: Job-Matching Service Sign-Up 

# Similar to the regression I ran above, The coefficients and R-squared values are 
# nearly identical but the p-values for wild boostrap and permutation test are mostly off and robust se is close

In [96]:
data = pd.read_stata("/Users/adishsundar/Desktop/Salem Center Research/WWOH Saudi/replication_package/data/clean_data/01_main_exp_clean.dta")
df = data
data.head()

,age,education,employed_now,employed_wife,children,haafez_self,vjobs_self,mwage_self,mwage_others,mwage_confidence,outside_self,outside_others,outside_confidence,semiseg_self,semiseg_others,semiseg_confidence,labor_demand_guess,session,signed_up_number,condition2,college_deg,married,num_know_per,num_mfs_per,stag,outside_guess,outside_objective,outside_wedge,semiseg_guess,semiseg_objective,semiseg_wedge,mwage_guess,mwage_objective,mwage_wedge,outside_wedge_pos,interaction
0,24.0,diploma,1,1,2,1,1,1,3,4,1,29,5,1,27,4,92.0,1,1.0,0.0,0.0,1.0,0.966667,0.500000,1,30.0,27.0,3.0,28.0,23.0,5.0,4.0,18.0,-14.0,1.0,0.0
1,20.0,secondary,1,1,2,1,1,0,12,3,1,22,3,1,14,2,27.0,1,0.0,1.0,0.0,1.0,0.966667,0.333333,0,23.0,27.0,-4.0,15.0,23.0,-8.0,12.0,18.0,-6.0,0.0,0.0
2,28.0,secondary,0,0,0,1,1,0,20,3,1,25,3,1,24,3,50.0,1,0.0,0.0,0.0,1.0,0.000000,0.000000,0,26.0,27.0,-1.0,25.0,23.0,2.0,20.0,18.0,2.0,0.0,0.0
3,18.0,secondary,1,0,1,1,1,1,15,4,1,19,5,1,26,4,20.0,1,0.0,0.0,0.0,1.0,0.966667,0.966667,0,20.0,27.0,-7.0,27.0,23.0,4.0,16.0,18.0,-2.0,0.0,0.0
4,29.0,bachelor,1,1,2,0,1,1,16,4,1,28,5,1,24,5,75.0,1,0.0,0.0,1.0,1.0,0.966667,0.333333,0,29.0,27.0,2.0,25.0,23.0,2.0,17.0,18.0,-1.0,1.0,0.0

In [97]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.iolib.summary2 import summary_col

# Identify columns ending with _self and _others
self_columns = [col for col in data.columns if col.endswith("_self")]
others_columns = [col for col in data.columns if col.endswith("_others")]

# Regression model specifications
model1 = 'signed_up_number ~ condition2'
model2 = 'signed_up_number ~ condition2 + C(session)'
model3 = 'signed_up_number ~ condition2 + C(session) + ' + ' + '.join(self_columns) + ' + ' + ' + '.join(others_columns)
model4 = 'signed_up_number ~ condition2 + C(session) + ' + ' + '.join(self_columns) + ' + ' + ' + '.join(others_columns) + ' + employed_wife + employed_now + C(education) + children + num_know_per + num_mfs_per + age'

# Fit regressions
reg1 = sm.OLS.from_formula(model1, data=data).fit()
reg2 = sm.OLS.from_formula(model2, data=data).fit()
reg3 = sm.OLS.from_formula(model3, data=data).fit()
reg4 = sm.OLS.from_formula(model4, data=data).fit()

# Create a summary table
summary_table = summary_col([reg1, reg2, reg3, reg4], model_names=['Model 1', 'Model 2', 'Model 3', 'Model 4'],
                            stars=True, float_format='%0.4f', regressor_order=['condition2', 'C(session)'] + self_columns + others_columns + ['employed_wife', 'employed_now', 'C(education)', 'children', 'num_know_per', 'num_mfs_per', 'age'])

# Print the summary table
print(summary_table)

===================================================================
                                Model 1  Model 2  Model 3  Model 4
-------------------------------------------------------------------
condition2                     0.0853**  0.0876** 0.0899** 0.0898**
                               (0.0400)  (0.0398) (0.0395) (0.0405)
haafez_self                                       0.0004   0.0080
                                                  (0.0661) (0.0704)
vjobs_self                                        0.0240   0.0355
                                                  (0.0548) (0.0581)
mwage_self                                        0.1057** 0.0967**
                                                  (0.0455) (0.0481)
outside_self                                      0.0537   0.0369
                                                  (0.0647) (0.0702)
semiseg_self                                      0.0439   0.0352
                                                  (0.0662) (0.0702)
mwage_others                                      0.0049*  0.0048*
                                                  (0.0028) (0.0029)
outside_others                                    -0.0013  -0.0016
                                                  (0.0031) (0.0032)
semiseg_others                                    0.0037   0.0038
                                                  (0.0030) (0.0031)
employed_wife                                              0.0391
                                                           (0.0493)
employed_now                                               -0.0726
                                                           (0.0674)
children                                                   0.0049
                                                           (0.0146)
num_know_per                                               -0.0834
                                                           (0.0628)
num_mfs_per                                                0.0885
                                                           (0.0664)
age                                                        0.0007
                                                           (0.0064)
C(education)[T.bachelor]                                   0.0324
                                                           (0.0651)
C(session)[T.6]                          0.1637   0.1165   0.1005
                                         (0.1137) (0.1136) (0.1230)
C(session)[T.8]                          0.2579** 0.2512** 0.2432**
                                         (0.1137) (0.1130) (0.1214)
C(session)[T.9]                          0.2063*  0.1922   0.1839
                                         (0.1168) (0.1177) (0.1236)
Intercept                      0.2348*** 0.1316   -0.1556  -0.1204
                               (0.0284)  (0.0819) (0.1190) (0.1878)
C(education)[T.diploma]                                    0.0146
                                                           (0.0641)
C(session)[T.7]                          0.0300   0.0350   0.0415
                                         (0.1147) (0.1142) (0.1213)
C(session)[T.5]                          0.2744** 0.2262*  0.2025
                                         (0.1147) (0.1154) (0.1257)
C(session)[T.12]                         0.0300   0.0043   -0.0297
                                         (0.1147) (0.1152) (0.1273)
C(education)[T.masters]                                    0.0175
                                                           (0.0906)
C(education)[T.middle]                                     0.1008
                                                           (0.1845)
C(education)[T.other_postgrad]                             -0.2670
                                                           (0.2023)
C(education)[T.phd]                                        -0.0082
                                                           (0.1585)
C(education)[T.primary]                                    0.0000
                                                           (0.0000)
C(education)[T.secondary]                                  -0.0104
                                                           (0.0642)
C(session)[T.10]                         -0.0075  -0.0154  -0.0142
                                         (0.1148) (0.1155) (0.1218)
C(session)[T.11]                         0.0203   0.0276   -0.0056
                                         (0.1119) (0.1109) (0.1199)
C(session)[T.13]                         0.1755   0.1642   0.1236
                                         (0.1159) (0.1169) (0.1277)
C(session)[T.4]                          0.1129   0.0756   0.0664
                                         (0.1140) (0.1153) (0.1199)
C(session)[T.14]                         0.2491** 0.2369** 0.2256*
                                         (0.1139) (0.1151) (0.1267)
C(session)[T.15]                         0.2024*  0.1956*  0.1796
                                         (0.1147) (0.1155) (0.1222)
C(session)[T.16]                         -0.1062  -0.0576  -0.0990
                                         (0.1169) (0.1179) (0.1269)
C(session)[T.17]                         -0.0420  -0.0682  -0.0834
                                         (0.1159) (0.1161) (0.1278)
C(session)[T.2]                          0.0624   0.0166   0.0450
                                         (0.1103) (0.1100) (0.1138)
C(session)[T.3]                          0.1019   0.0776   0.1018
                                         (0.1147) (0.1150) (0.1181)
R-squared                      0.0091    0.0696   0.1083   0.1158
R-squared Adj.                 0.0071    0.0368   0.0613   0.0436
===================================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

In [98]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.iolib.summary2 import summary_col

# Regression model specifications
model1 = 'signed_up_number ~ condition2'
model2 = 'signed_up_number ~ condition2 + C(session)'
model3 = 'signed_up_number ~ condition2 + C(session) + ' + ' + '.join(self_columns) + ' + ' + ' + '.join(others_columns)
model4 = 'signed_up_number ~ condition2 + C(session) + ' + ' + '.join(self_columns) + ' + ' + ' + '.join(others_columns) + ' + employed_wife + employed_now + C(education) + children + num_know_per + num_mfs_per + age'

# Fit regressions
reg1 = sm.OLS.from_formula(model1, data=data).fit(cov_type='HC3')  # Robust standard errors
reg2 = sm.OLS.from_formula(model2, data=data).fit(cov_type='HC3')
reg3 = sm.OLS.from_formula(model3, data=data).fit(cov_type='HC3')
reg4 = sm.OLS.from_formula(model4, data=data).fit(cov_type='HC3')

# Extract p-values
p_values = [
    reg1.pvalues['condition2'],
    reg2.pvalues['condition2'],
    reg3.pvalues['condition2'],
    reg4.pvalues['condition2']
]

# Create a DataFrame for p-values
p_values_df = pd.DataFrame({"p-value (robust SE)": p_values})

# Print the p-values DataFrame
print(p_values_df)

   p-value (robust SE)
0             0.032911
1             0.030988
2             0.026276
3             0.032195

In [106]:
# Perform wild bootstrap for each model
wboot1 = reg1.get_robustcov_results().pvalues[0]
wboot2 = reg2.get_robustcov_results().pvalues[0]
wboot3 = reg3.get_robustcov_results().pvalues[0]
wboot4 = reg4.get_robustcov_results().pvalues[0]

# Create a DataFrame for wild bootstrap p-values
wboot_p_values_df = pd.DataFrame({"p-value (wild bootstrap)": [wboot1, wboot2, wboot3, wboot4]})

# Print the wild bootstrap p-values DataFrame
print(wboot_p_values_df)

   p-value (wild bootstrap)
0              3.661950e-18
1              7.493173e-02
2              1.086571e-01
3              4.880709e-01

In [111]:
import pandas as pd
from mlxtend.evaluate import permutation_test
import statsmodels.api as sm

# Create observed values and expected values for each model
observed_values = [reg.model.endog for reg in [reg1, reg2, reg3, reg4]]
expected_values = [reg.fittedvalues for reg in [reg1, reg2, reg3, reg4]]

# Perform permutation test for each model
perm_test_results = [permutation_test(obs, exp, method='approximate', num_rounds=1000) for obs, exp in zip(observed_values, expected_values)]

# Extract p-values from permutation test results
perm_p_values = [result for result in perm_test_results]

# Create a DataFrame for permutation test p-values
perm_p_values_df = pd.DataFrame({"Model": [f"Model {i+1}" for i in range(4)],
                                  "Permutation Test P-Value": perm_p_values})

# Print the permutation test p-values DataFrame
print(perm_p_values_df)

     Model  Permutation Test P-Value
0  Model 1                       1.0
1  Model 2                       1.0
2  Model 3                       1.0
3  Model 4                       1.0